### ISSUE TITLE
Investment Reports will not run on 2023.1 onwards

### ISSUE THREAD

**Issue by yogi1967** [dkfurrow/moneydance-investment-reports#5]
Refer: 
https://infinitekind.tenderapp.com/discussions/investments/8006-investment-reports-will-not-run

Console reports:

```
com.moneydance.modules.features.invextension.LogController logException 
SEVERE: Error in transaction values calculation: Sippdeal ISA Security: Legal & General Group PLC Date: 05/06/2023 
com.moneydance.modules.features.invextension.TransactionValues$InitialTransactionException: Error in investment account: Sippdeal ISA Security: Legal & General Group PLC must start with either a Buy, BuyXfer or Short, but instead starts with a DIVIDEND
at com.moneydance.modules.features.invextension.TransactionValues.throwInitialTransactionException(TransactionValues.java:488)
at com.moneydance.modules.features.invextension.TransactionValues.<init>(TransactionValues.java:232) 
at com.moneydance.modules.features.invextension.SecurityAccountWrapper.generateTransValues(SecurityAccountWrapper.java:109)
at com.moneydance.modules.features.invextension.SecurityAccountWrapper.<init>(SecurityAccountWrapper.java:67) 
at com.moneydance.modules.features.invextension.InvestmentAccountWrapper.<init>(InvestmentAccountWrapper.java:76) 
at com.moneydance.modules.features.invextension.BulkSecInfo.getInvestmentAccountInfo(BulkSecInfo.java:417)
at com.moneydance.modules.features.invextension.BulkSecInfo.<init>(BulkSecInfo.java:135) 
at com.moneydance.modules.features.invextension.MDData.generateCurrentInfo(MDData.java:77)
at com.moneydance.modules.features.invextension.ReportControlPanel$ReportExecutor.doInBackground(ReportControlPanel.java:930)
at com.moneydance.modules.features.invextension.ReportControlPanel$ReportExecutor.doInBackground(ReportControlPanel.java:915)
at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source) 
at java.base/java.util.concurrent.FutureTask.run(Unknown Source) 
at java.desktop/javax.swing.SwingWorker.run(Unknown Source) 
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 
at java.base/java.lang.Thread.run(Unknown Source)


```

Can you help identify why this error is occurring? Thanks

**Comment by dkfurrow** [comment]
Cross-posted from moneydance chat boards, response there.

**Comment by yogi1967** [comment]
I cannot see any response on the MD chat board thread?

**Comment by dkfurrow** [comment]
There now.
